# Generated by Django 4.0.6 on 2022-08-18 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_ticket_deleted_ticket_email_alter_ticket_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='exists',
            field=models.IntegerField(default=0),
        ),
    ]
