# Generated by Django 4.0.6 on 2022-08-19 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_flight_exists'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='searchdate',
            field=models.DateField(default=None),
        ),
    ]
