# Generated by Django 4.0.6 on 2022-08-19 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_flight_searchdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='searchdate',
        ),
    ]
