# Generated by Django 4.0.6 on 2024-02-24 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0005_remove_flight_searchdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='code',
            new_name='num',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='exists',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='gender',
        ),
    ]
