# Generated by Django 4.0.6 on 2024-02-25 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0007_flight_exists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='num',
            new_name='code',
        ),
    ]
